import { useQuery, useMutation } from '@tanstack/react-query';
import { aiService } from '@/services/api';
import type { AgentType, PlannerSettings } from '@/types';
import toast from 'react-hot-toast';

export function useAIInsights() {
  return useQuery({
    queryKey: ['ai-insights'],
    queryFn: aiService.getInsights,
    staleTime: 10 * 60 * 1000,
  });
}

export function useAIPrioritize() {
  return useMutation({
    mutationFn: (taskIds: string[]) => aiService.prioritize(taskIds),
    onSuccess: () => {
      toast.success('Tasks prioritized by AI');
    },
    onError: () => {
      toast.error('Failed to prioritize tasks');
    },
  });
}

export function useAIBreakdown() {
  return useMutation({
    mutationFn: (taskId: string) => aiService.breakdownTask(taskId),
    onSuccess: () => {
      toast.success('Task broken down into subtasks');
    },
    onError: () => {
      toast.error('Failed to break down task');
    },
  });
}

export function useAIGeneratePlan() {
  return useMutation({
    mutationFn: (settings: PlannerSettings) => aiService.generatePlan(settings),
    onSuccess: () => {
      toast.success('Daily plan generated by AI');
    },
    onError: () => {
      toast.error('Failed to generate plan');
    },
  });
}

export function useAIChat() {
  return useMutation({
    mutationFn: ({
      message,
      agentType,
      context,
    }: {
      message: string;
      agentType: AgentType;
      context?: Record<string, unknown>;
    }) => aiService.chat(message, agentType, context),
    onError: () => {
      toast.error('AI failed to respond. Please try again.');
    },
  });
}
