import type {
  Task,
  DailyPlan,
  AIInsight,
  ProductivityMetrics,
  AppNotification,
  User,
  WeeklyData,
  CategoryBreakdown,
} from '@/types';

export const mockUser: User = {
  id: 'user-1',
  email: 'demo@focusflow.ai',
  name: 'Alex Developer',
  preferences: {
    theme: 'system',
    energyPattern: 'morning',
    workStartTime: '09:00',
    workEndTime: '17:00',
    breakDuration: 15,
    focusBlockDuration: 90,
    notifications: {
      deadlineReminder: true,
      dailyDigest: true,
      overdueAlert: true,
      productivityInsights: true,
    },
    categories: ['Work', 'Personal', 'Health', 'Learning'],
  },
  createdAt: '2024-01-01T00:00:00Z',
};

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    userId: 'user-1',
    title: 'Design new landing page',
    description: 'Create a modern, conversion-optimized landing page for the product launch',
    priority: 'high',
    status: 'in_progress',
    category: 'Work',
    tags: ['design', 'frontend', 'launch'],
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedMinutes: 180,
    progress: 45,
    subtasks: [
      { id: 'st-1', title: 'Wireframe layout', completed: true, estimatedMinutes: 30 },
      { id: 'st-2', title: 'Design hero section', completed: true, estimatedMinutes: 45 },
      { id: 'st-3', title: 'Design features section', completed: false, estimatedMinutes: 45 },
      { id: 'st-4', title: 'Responsive design', completed: false, estimatedMinutes: 60 },
    ],
    order: 1,
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-03T14:00:00Z',
  },
  {
    id: 'task-2',
    userId: 'user-1',
    title: 'Implement authentication system',
    description: 'Set up JWT-based auth with Cognito integration',
    priority: 'critical',
    status: 'todo',
    category: 'Work',
    tags: ['backend', 'security', 'aws'],
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedMinutes: 240,
    progress: 0,
    subtasks: [],
    order: 2,
    createdAt: '2024-03-02T09:00:00Z',
    updatedAt: '2024-03-02T09:00:00Z',
  },
  {
    id: 'task-3',
    userId: 'user-1',
    title: 'Weekly team standup notes',
    description: 'Prepare and share notes from weekly standup meeting',
    priority: 'medium',
    status: 'completed',
    category: 'Work',
    tags: ['meetings', 'communication'],
    estimatedMinutes: 30,
    progress: 100,
    subtasks: [],
    order: 3,
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2024-03-03T10:00:00Z',
    completedAt: '2024-03-03T10:00:00Z',
  },
  {
    id: 'task-4',
    userId: 'user-1',
    title: 'Exercise routine - 30min cardio',
    description: 'Morning cardio session at the gym',
    priority: 'medium',
    status: 'todo',
    category: 'Health',
    tags: ['exercise', 'routine'],
    dueDate: new Date(Date.now()).toISOString(),
    estimatedMinutes: 45,
    progress: 0,
    subtasks: [],
    order: 4,
    createdAt: '2024-03-03T07:00:00Z',
    updatedAt: '2024-03-03T07:00:00Z',
  },
  {
    id: 'task-5',
    userId: 'user-1',
    title: 'Read TypeScript design patterns book',
    description: 'Chapter 5-7 on advanced patterns',
    priority: 'low',
    status: 'in_progress',
    category: 'Learning',
    tags: ['reading', 'typescript'],
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedMinutes: 120,
    progress: 30,
    subtasks: [
      { id: 'st-5', title: 'Chapter 5: Creational Patterns', completed: true, estimatedMinutes: 40 },
      { id: 'st-6', title: 'Chapter 6: Structural Patterns', completed: false, estimatedMinutes: 40 },
      { id: 'st-7', title: 'Chapter 7: Behavioral Patterns', completed: false, estimatedMinutes: 40 },
    ],
    order: 5,
    createdAt: '2024-02-28T18:00:00Z',
    updatedAt: '2024-03-02T20:00:00Z',
  },
  {
    id: 'task-6',
    userId: 'user-1',
    title: 'Write API documentation',
    description: 'Document all REST API endpoints with examples',
    priority: 'high',
    status: 'todo',
    category: 'Work',
    tags: ['documentation', 'api'],
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedMinutes: 150,
    progress: 0,
    subtasks: [],
    order: 6,
    createdAt: '2024-03-03T11:00:00Z',
    updatedAt: '2024-03-03T11:00:00Z',
  },
];

export const mockDailyPlan: DailyPlan = {
  id: 'plan-1',
  userId: 'user-1',
  date: new Date().toISOString().split('T')[0],
  timeBlocks: [
    { id: 'tb-1', title: 'Morning Focus: Auth System', taskId: 'task-2', startTime: '09:00', endTime: '10:30', type: 'focus' },
    { id: 'tb-2', title: 'Break', startTime: '10:30', endTime: '10:45', type: 'break' },
    { id: 'tb-3', title: 'Landing Page Design', taskId: 'task-1', startTime: '10:45', endTime: '12:00', type: 'task' },
    { id: 'tb-4', title: 'Lunch', startTime: '12:00', endTime: '13:00', type: 'personal' },
    { id: 'tb-5', title: 'Team Standup', startTime: '13:00', endTime: '13:30', type: 'meeting' },
    { id: 'tb-6', title: 'API Documentation', taskId: 'task-6', startTime: '13:30', endTime: '15:00', type: 'task' },
    { id: 'tb-7', title: 'Break', startTime: '15:00', endTime: '15:15', type: 'break' },
    { id: 'tb-8', title: 'Reading: TS Patterns', taskId: 'task-5', startTime: '15:15', endTime: '16:00', type: 'task' },
    { id: 'tb-9', title: 'Wrap-up & Planning', startTime: '16:00', endTime: '17:00', type: 'task' },
  ],
  availableHours: 8,
  energyPattern: 'morning',
  createdAt: new Date().toISOString(),
};

export const mockInsights: AIInsight[] = [
  {
    id: 'insight-1',
    type: 'suggestion',
    title: 'Optimize Your Morning',
    content: 'You complete 40% more tasks between 9-11 AM. Consider scheduling your critical tasks during this window.',
    confidence: 0.88,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'insight-2',
    type: 'burnout_warning',
    title: 'Workload Alert',
    content: 'You have been working 10+ hours for 3 consecutive days. Consider taking a longer break to avoid burnout.',
    confidence: 0.92,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'insight-3',
    type: 'focus_tip',
    title: 'Deep Work Block',
    content: 'Your authentication task requires deep focus. Block a 2-hour uninterrupted session for optimal progress.',
    confidence: 0.85,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'insight-4',
    type: 'motivation',
    title: 'Great Progress!',
    content: 'You completed 12 tasks this week, which is 30% more than last week. Keep up the momentum!',
    confidence: 0.95,
    createdAt: new Date(Date.now() - 10800000).toISOString(),
  },
];

export const mockWeeklyData: WeeklyData[] = [
  { day: 'Mon', completed: 5, created: 3, focusMinutes: 180 },
  { day: 'Tue', completed: 3, created: 4, focusMinutes: 150 },
  { day: 'Wed', completed: 7, created: 2, focusMinutes: 210 },
  { day: 'Thu', completed: 4, created: 5, focusMinutes: 165 },
  { day: 'Fri', completed: 6, created: 3, focusMinutes: 195 },
  { day: 'Sat', completed: 2, created: 1, focusMinutes: 60 },
  { day: 'Sun', completed: 1, created: 2, focusMinutes: 45 },
];

export const mockCategoryBreakdown: CategoryBreakdown[] = [
  { category: 'Work', count: 15, completedCount: 10, totalMinutes: 2400 },
  { category: 'Personal', count: 5, completedCount: 4, totalMinutes: 300 },
  { category: 'Health', count: 7, completedCount: 5, totalMinutes: 420 },
  { category: 'Learning', count: 4, completedCount: 2, totalMinutes: 600 },
];

export const mockMetrics: ProductivityMetrics = {
  tasksCompleted: 28,
  tasksPending: 12,
  completionRate: 70,
  averageCompletionTime: 45,
  streakDays: 5,
  totalFocusMinutes: 1005,
  weeklyData: mockWeeklyData,
  categoryBreakdown: mockCategoryBreakdown,
  aiProductivityScore: 78,
};

export const mockNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    type: 'deadline',
    title: 'Deadline Tomorrow',
    message: 'Implement authentication system is due tomorrow',
    read: false,
    taskId: 'task-2',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notif-2',
    type: 'insight',
    title: 'New AI Insight',
    message: 'Your productivity score increased by 15% this week',
    read: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif-3',
    type: 'achievement',
    title: '5-Day Streak!',
    message: 'You have completed tasks for 5 consecutive days',
    read: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'notif-4',
    type: 'overdue',
    title: 'Task Overdue',
    message: 'Exercise routine - 30min cardio was due today',
    read: true,
    taskId: 'task-4',
    createdAt: new Date(Date.now() - 43200000).toISOString(),
  },
];
